server:
  address: 127.0.0.1        # Linux允许0.0.0.0或127.0.0.1  Windows只能是127.0.0.1
  port: 8999
  password: changethis
users:
  - bili.yaml
# - user0.yaml
# - user1.yaml
# - user100.yaml
# - userN.yaml
bilibili:
  appkey: 1d8b6e7d45233436
  app_secret: 560c52ccd288fed045859ed18bffd973
