servers:
  - address: 127.0.0.1
    port: 8999
    password: changethis
  - address: 35.155.238.15
    port: 8999
    password: changethis
  - address: fab08.cecs.pdx.edu
    port: 8999
    password: changethis
  - address: fab09.cecs.pdx.edu
    port: 8999
    password: changethis
  - address: fab10.cecs.pdx.edu
    port: 8999
    password: changethis
  - address: 54.213.157.246
    port: 8999
    password: changethis
users:
  - bili.yaml
  - user0.yaml
  - user2.yaml
bilibili:
  appkey: 1d8b6e7d45233436
  app_secret: 560c52ccd288fed045859ed18bffd973
